# Generated by Django 6.0.7 on 2026-07-31 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('phone', models.CharField(max_length=20)),
                ('whatsapp', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('state', models.CharField(max_length=100)),
                ('lga', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('course', models.CharField(choices=[('Laptop Engineering', 'Laptop Engineering'), ('Smartphone Engineering', 'Smartphone Engineering'), ('Python Programming', 'Python Programming'), ('JavaScript & Web Development', 'JavaScript & Web Development'), ('IT System Administration', 'IT System Administration')], max_length=100)),
                ('training_mode', models.CharField(choices=[('Physical', 'Physical'), ('Online', 'Online'), ('Hybrid', 'Hybrid')], max_length=20)),
                ('passport', models.ImageField(upload_to='students/')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
